<?php

namespace App\Support;

enum ErrorLogEnum:string
{
    // Products
    case GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

    // Order
    case GET_ORDERS_ACTION_ERROR = 'GET_ORDERS_ACTION_ERROR';
    case STORE_ORDER_ACTION_ERROR = 'STORE_ORDER_ACTION_ERROR';
    case GET_CUSTOMER_ORDERS_ACTION_ERROR = 'GET_CUSTOMER_ORDERS_ACTION_ERROR';

    // Customer
    case STORE_CUSTOMER_ACTION_ERROR = 'STORE_CUSTOMER_ACTION_ERROR';
    case STORE_CUSTOMER_ADDRESS_ACTION_ERROR = 'STORE_CUSTOMER_ADDRESS_ACTION_ERROR';
    case GET_CUSTOMER_BY_SESSION_ID_ACTION_ERROR = 'GET_CUSTOMER_BY_SESSION_ID_ACTION_ERROR';
}
